server:
  port: 9010

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpay-merchant-db}

jwt:
  secret-key: eibccbtbiklkhuhhlglihrntcfdvggdfdtikfkdbkbhb

app:
  merchant-context:
    filter-enabled: true

webhook:
  secret-encryption-key: eibccbtbiklkrrbfrehknkncrjhftlug
