server:
  port: 9030

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpay-operations-db}

app:
  webhook:
    delivery:
      redis-key: "webhook-retry"
  merchant-context:
    filter-enabled: true
