server:
  port: 9040

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpay-vault-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Akg@1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

vault:
  master-key: eibccbtbiklkrrbfrehknkncrjhftlug

app:
  merchant-context:
    filter-enabled: true

resilience4j:
  thread-pool-bulkhead:
    instances:
      vault-card-processor:
        core-thread-pool-size: 5
        max-thread-pool-size: 10
        queue-capacity: 20
